# Generated by Django 5.0.4 on 2024-06-18 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mydetails", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="techstack",
            old_name="techstack",
            new_name="techstacklist",
        ),
    ]
