# Generated by Django 5.0.4 on 2024-06-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mydetails", "0003_delete_techstack"),
    ]

    operations = [
        migrations.CreateModel(
            name="techstack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("techstacklist1", models.CharField(max_length=500)),
                ("techstacklist2", models.CharField(max_length=500)),
            ],
        ),
    ]
