# Generated by Django 5.0.4 on 2024-06-18 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mydetails", "0004_techstack"),
    ]

    operations = [
        migrations.DeleteModel(
            name="aboutpage",
        ),
        migrations.DeleteModel(
            name="techstack",
        ),
    ]
