# Generated by Django 5.0.4 on 2024-06-18 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mydetails", "0008_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="aboutpage",
        ),
        migrations.DeleteModel(
            name="Techstack",
        ),
    ]
