# Generated by Django 5.0.4 on 2024-06-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mydetails", "0009_delete_aboutpage_delete_techstack"),
    ]

    operations = [
        migrations.CreateModel(
            name="aboutpage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Hobbies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hb1", models.CharField(max_length=500)),
                ("hb2", models.CharField(max_length=500)),
                ("hb3", models.CharField(max_length=500)),
                ("hb4", models.CharField(max_length=500)),
            ],
        ),
    ]
