# Generated by Django 5.0.4 on 2024-06-18 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mydetails", "0010_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hobbies",
            new_name="Hobbies1",
        ),
    ]
