# Generated by Django 5.0.4 on 2024-06-18 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "mydetails",
            "0013_rename_eduction_category_details_education_category_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Education_category",
            new_name="Education_category1",
        ),
    ]
