# Generated by Django 5.0.4 on 2024-06-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mydetails", "0016_skills1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exp1_sub", models.CharField(max_length=500)),
                ("exp1_desc", models.CharField(max_length=500)),
                ("exp1_year", models.IntegerField(max_length=100)),
                ("exp2_sub", models.CharField(max_length=500)),
                ("exp2_desc", models.CharField(max_length=500)),
                ("exp2_year", models.IntegerField(max_length=100)),
                ("exp3_sub", models.CharField(max_length=500)),
                ("exp3_desc", models.CharField(max_length=500)),
                ("exp3_year", models.IntegerField(max_length=100)),
                ("exp4_sub", models.CharField(max_length=500)),
                ("exp4_desc", models.CharField(max_length=500)),
                ("exp4_year", models.IntegerField(max_length=100)),
                ("exp5_sub", models.CharField(max_length=500)),
                ("exp5_desc", models.CharField(max_length=500)),
                ("exp5_year", models.IntegerField(max_length=100)),
                ("exp6_sub", models.CharField(max_length=500)),
                ("exp6_desc", models.CharField(max_length=500)),
                ("exp6_year", models.IntegerField(max_length=100)),
                ("exp7_sub", models.CharField(max_length=500)),
                ("exp7_desc", models.CharField(max_length=500)),
                ("exp7_year", models.IntegerField(max_length=100)),
            ],
        ),
    ]
