# Generated by Django 5.0.4 on 2024-06-18 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mydetails", "0002_rename_techstack_techstack_techstacklist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="techstack",
        ),
    ]
