# Generated by Django 5.0.4 on 2024-06-18 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mydetails", "0006_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="aboutpage",
        ),
        migrations.DeleteModel(
            name="Techstack",
        ),
    ]
