# Generated by Django 5.0.4 on 2024-06-18 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mydetails", "0012_eduction_category_eduction_category_details"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Eduction_category_details",
            new_name="Education_category",
        ),
        migrations.RenameModel(
            old_name="Eduction_category",
            new_name="Education_category_details",
        ),
        migrations.RenameField(
            model_name="education_category",
            old_name="ed1_details",
            new_name="ed1",
        ),
        migrations.RenameField(
            model_name="education_category",
            old_name="ed2_details",
            new_name="ed2",
        ),
        migrations.RenameField(
            model_name="education_category",
            old_name="ed3_details",
            new_name="ed3",
        ),
        migrations.RenameField(
            model_name="education_category",
            old_name="ed4_details",
            new_name="ed4",
        ),
        migrations.RenameField(
            model_name="education_category_details",
            old_name="ed1",
            new_name="ed1_details",
        ),
        migrations.RenameField(
            model_name="education_category_details",
            old_name="ed2",
            new_name="ed2_details",
        ),
        migrations.RenameField(
            model_name="education_category_details",
            old_name="ed3",
            new_name="ed3_details",
        ),
        migrations.RenameField(
            model_name="education_category_details",
            old_name="ed4",
            new_name="ed4_details",
        ),
    ]
